### ISSUE TITLE
About pipeline of this repo？

### ISSUE THREAD

**Issue by KangolHsu** [EunhyeokPark/script_for_FQ#1]
1.I train my float model first，
2.Then I use your script ‘transfer.py’ generate fq model and fq prototxt，
3.Then i use this two file to finetune and get the final fq model。

am i right? and some weights of  the final model is below:
conv1_weight:
0.223883, -0.034048, 0.007305, -0.162069, -0.259445, 0.203687, 0.188909, 0.194916, 0.062153, 0.117690, -0.230910, 0.127371, 0.177634, 0.154927, -0.109744, 0.095113, 0.077550, 0.099198, -0.152189, -0.133082, 0.153672, 0.069281, -0.049735, 0.151197, 0.160376, -0.177887, -0.040646, -0.130443, 0.086173, 0.065225, -0.121238, 0.057039, 0.227713, 0.038241, -0.066757, -0.141908, -0.076439, -0.216041, 0.073697, .............

it is not all in ’power of two‘ type number。what‘s you quantization mean？ thanks

**Comment by EunhyeokPark** [comment]
Your training pipeline is correct.

In the case of stored weight, my code doesn't store the quantized value into the network blob. Instead, the modified FQ layers have its own quant_ blob to store the quantized parameter. When the network is forwarded, the quantization parameters are checked whether the quantization is required or not and, if necessary, quantization is applied to the weight and the quantized value is stored in the quant_ blob. Thus, you are unable to access the quantized weight. Instead, you can manually generate the quantized weight based on the accessible quantization parameters.

**Comment by KangolHsu** [comment]
@EunhyeokPark 
I found that FQconvolution had three blobs ，the first is weights，the second is bias，the last is ？。
you said i can manually generate the quantized weight based on the accessible quantization parameters。can you specify where is the  quantization parameters，and where is the code i should dive into ？
many thanks for your apply。

**Comment by EunhyeokPark** [comment]
The last blob stores quantization information, which is represented by four values.

First value stores the number of quantization level, second value stores the difference of quantization level, third and fourth value store min and max index of quantization respectably.

By taking advantage of above information, weight is quantized. The quantization code can be found at CAFFE_ROOT/src/caffe/util/quant_functions.cu
